DROP TABLE IF EXISTS igralci_1617;
DROP TABLE IF EXISTS igralci_1718;
DROP TABLE IF EXISTS igralci_1819;

CREATE TABLE IF NOT EXISTS igralci_1617(
   IGRALEC  VARCHAR(20) NOT NULL PRIMARY KEY
  ,EKIPA    VARCHAR(3)
  ,POZICIJA VARCHAR(2)
  ,STAROST  INTEGER 
  ,VISINA   VARCHAR(4)
  ,TEZA     INTEGER 
  ,DRZAVA   VARCHAR(16)
  ,GP       INTEGER 
  ,MPG      NUMERIC(4,1)
  ,PPG      NUMERIC(4,1)
  ,APG      NUMERIC(4,1)
  ,RPG      NUMERIC(4,1)
  ,SPG      NUMERIC(4,2)
  ,FT       NUMERIC(5,3)
  ,DVA      NUMERIC(5,3)
  ,TRI      NUMERIC(5,3)
);

CREATE TABLE IF NOT EXISTS igralci_1718(
   IGRALEC  VARCHAR(24) NOT NULL PRIMARY KEY
  ,EKIPA    VARCHAR(3)
  ,POZICIJA VARCHAR(2)
  ,STAROST  INTEGER 
  ,VISINA   VARCHAR(4)
  ,TEZA     INTEGER 
  ,DRZAVA   VARCHAR(16)
  ,GP       INTEGER 
  ,MPG      NUMERIC(4,1)
  ,PPG      NUMERIC(4,1)
  ,APG      NUMERIC(4,1)
  ,RPG      NUMERIC(4,1)
  ,SPG      NUMERIC(4,2)
  ,FT       NUMERIC(5,3)
  ,DVA      NUMERIC(5,3)
  ,TRI      NUMERIC(5,3)
);

CREATE TABLE IF NOT EXISTS igralci_1819(
   IGRALEC  VARCHAR(24) NOT NULL PRIMARY KEY
  ,EKIPA    VARCHAR(3) NOT NULL
  ,POZICIJA VARCHAR(3) NOT NULL
  ,STAROST  INTEGER  NOT NULL
  ,VISINA   VARCHAR(4) NOT NULL
  ,TEZA     INTEGER  NOT NULL
  ,DRZAVA   VARCHAR(16) NOT NULL
  ,GP       INTEGER  NOT NULL
  ,MPG      NUMERIC(4,1) NOT NULL
  ,PPG      NUMERIC(4,1) NOT NULL
  ,APG      NUMERIC(4,1) NOT NULL
  ,RPG      NUMERIC(4,1) NOT NULL
  ,SPG      NUMERIC(4,2) NOT NULL
  ,FT       NUMERIC(5,3) NOT NULL
  ,DVA      NUMERIC(5,3) NOT NULL
  ,TRI      NUMERIC(5,3) NOT NULL
);