INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (1,'Atlanta Hawks','ATL','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (2,'Boston Celtics','BOS','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (3,'Brooklyn Nets','BKN','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (4,'Charlotte Hornets','CHA','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (5,'Chicago Bulls','CHI','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (6,'Cleveland Cavaliers','CLE','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (7,'Dallas Mavericks','DAL','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (8,'Denver Nuggets','DEN','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (9,'Detroit Pistons','DET','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (10,'Golden State Warriors','GSW','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (11,'Houston Rockets','HOU','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (12,'Indiana Pacers','IND','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (13,'Los Angeles Clippers','LAC','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (14,'Los Angeles Lakers','LAL','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (15,'Memphis Grizzlies','MEM','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (16,'Miami Heat','MIA','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (17,'Milwaukee Bucks','MIL','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (18,'Minnesota Timberwolves','MIN','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (19,'New Orleans Pelicans','NOP','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (20,'New York Knicks','NYK','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (21,'Oklahoma City Thunder','OKC','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (22,'Orlando Magic','ORL','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (23,'Philadelphia 76ers','PHI','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (24,'Phoenix Suns','PHX','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (25,'Portland Trail Blazers','POR','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (26,'Sacramento Kings','SAC','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (27,'San Antonio Spurs','SAS','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (28,'Toronto Raptors','TOR','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (29,'Utah Jazz','UTA','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (30,'Washington Wizards','WAS','NA',16);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (31,'Atlanta Hawks','ATL','Sharecare',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (32,'Boston Celtics','BOS','General Electric',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (33,'Brooklyn Nets','BKN','Infor',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (34,'Charlotte Hornets','CHA','LendingTree',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (35,'Chicago Bulls','CHI','NA',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (36,'Cleveland Cavaliers','CLE','Goodyear',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (37,'Dallas Mavericks','DAL','NA',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (38,'Denver Nuggets','DEN','Western Union',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (39,'Detroit Pistons','DET','Flagstar Bank',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (40,'Golden State Warriors','GSW','Rakuten',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (41,'Houston Rockets','HOU','NA',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (42,'Indiana Pacers','IND','NA',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (43,'Los Angeles Clippers','LAC','NA',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (44,'Los Angeles Lakers','LAL','Wish',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (45,'Memphis Grizzlies','MEM','NA',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (46,'Miami Heat','MIA','Ultimate Software',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (47,'Milwaukee Bucks','MIL','Harley Davidson',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (48,'Minnesota Timberwolves','MIN','Fitbit',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (49,'New Orleans Pelicans','NOP','Zatarain''s',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (50,'New York Knicks','NYK','Squarespace',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (51,'Oklahoma City Thunder','OKC','NA',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (52,'Orlando Magic','ORL','Disney',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (53,'Philadelphia 76ers','PHI','StubHub',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (54,'Phoenix Suns','PHX','NA',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (55,'Portland Trail Blazers','POR','NA',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (56,'Sacramento Kings','SAC','Blue Diamond Almonds',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (57,'San Antonio Spurs','SAS','NA',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (58,'Toronto Raptors','TOR','Sun Life',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (59,'Utah Jazz','UTA','Qualtrics (5 for the fight)',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (60,'Washington Wizards','WAS','NA',17);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (61,'Atlanta Hawks','ATL','Sharecare',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (62,'Boston Celtics','BOS','General Electric',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (63,'Brooklyn Nets','BKN','Infor',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (64,'Charlotte Hornets','CHA','LendingTree',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (65,'Chicago Bulls','CHI','Zenni Optical',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (66,'Cleveland Cavaliers','CLE','Goodyear',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (67,'Dallas Mavericks','DAL','5Miles',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (68,'Denver Nuggets','DEN','Western Union',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (69,'Detroit Pistons','DET','Flagstar Bank',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (70,'Golden State Warriors','GSW','Rakuten',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (71,'Houston Rockets','HOU','Rokit Phones',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (72,'Indiana Pacers','IND','Motorola',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (73,'Los Angeles Clippers','LAC','Bumble',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (74,'Los Angeles Lakers','LAL','Wish',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (75,'Memphis Grizzlies','MEM','FedEx',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (76,'Miami Heat','MIA','Ultimate Software',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (77,'Milwaukee Bucks','MIL','Harley Davidson',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (78,'Minnesota Timberwolves','MIN','Fitbit',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (79,'New Orleans Pelicans','NOP','Zatarain''s',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (80,'New York Knicks','NYK','Squarespace',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (81,'Oklahoma City Thunder','OKC','NA',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (82,'Orlando Magic','ORL','Disney',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (83,'Philadelphia 76ers','PHI','StubHub',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (84,'Phoenix Suns','PHX','PayPal',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (85,'Portland Trail Blazers','POR','Biofreeze',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (86,'Sacramento Kings','SAC','Blue Diamond Almonds',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (87,'San Antonio Spurs','SAS','Frost Bank',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (88,'Toronto Raptors','TOR','Sun Life',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (89,'Utah Jazz','UTA','Qualtrics (5 for the fight)',18);
INSERT INTO ekipe(ID,Ime_ekipe,Kratica,Sponzor_na_dresu,Sezona) VALUES (90,'Washington Wizards','WAS','Geico',18);