INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Atlanta Hawks','ATL','Sharecare');
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Boston Celtics','BOS','General Electric');
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Brooklyn Nets','BKN','Infor');
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Charlotte Hornets','CHA','LendingTree');
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Chicago Bulls','CHI',NULL);
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Cleveland Cavaliers','CLE','Goodyear');
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Dallas Mavericks','DAL',NULL);
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Denver Nuggets','DEN','Western Union');
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Detroit Pistons','DET','Flagstar Bank');
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Golden State Warriors','GSW','Rakuten');
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Houston Rockets','HOU',NULL);
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Indiana Pacers','IND',NULL);
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Los Angeles Clippers','LAC',NULL);
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Los Angeles Lakers','LAL','Wish');
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Memphis Grizzlies','MEM',NULL);
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Miami Heat','MIA','Ultimate Software');
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Milwaukee Bucks','MIL','Harley Davidson');
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Minnesota Timberwolves','MIN','Fitbit');
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('New Orleans Pelicans','NOP','Zatarain’s');
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('New York Knicks','NYK','Squarespace');
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Oklahoma City Thunder','OKC',NULL);
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Orlando Magic','ORL','Disney');
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Philadelphia 76ers','PHI','StubHub');
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Phoenix Suns','PHX',NULL);
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Portland Trail Blazers','POR',NULL);
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Sacramento Kings','SAC','Blue Diamond Almonds');
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('San Antonio Spurs','SAS',NULL);
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Toronto Raptors','TOR','Sun Life');
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Utah Jazz','UTA','Qualtrics (5 for the fight)');
INSERT INTO sponzorji_1718(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Washington Wizards','WAS',NULL);
