INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Atlanta Hawks','ATL','Sharecare');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Boston Celtics','BOS','General Electric');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Brooklyn Nets','BKN','Infor');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Charlotte Hornets','CHA','LendingTree');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Chicago Bulls','CHI','Zenni Optical');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Cleveland Cavaliers','CLE','Goodyear');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Dallas Mavericks','DAL','5Miles');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Denver Nuggets','DEN','Western Union');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Detroit Pistons','DET','Flagstar Bank');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Golden State Warriors','GSW','Rakuten');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Houston Rockets','HOU','Rokit Phones');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Indiana Pacers','IND','Motorola');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Los Angeles Clippers','LAC','Bumble');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Los Angeles Lakers','LAL','Wish');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Memphis Grizzlies','MEM','FedEx');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Miami Heat','MIA','Ultimate Software');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Milwaukee Bucks','MIL','Harley Davidson');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Minnesota Timberwolves','MIN','Fitbit');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('New Orleans Pelicans','NOP','Zatarain''s');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('New York Knicks','NYK','Squarespace');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Oklahoma City Thunder','OKC',NULL);
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Orlando Magic','ORL','Disney');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Philadelphia 76ers','PHI','StubHub');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Phoenix Suns','PHX','PayPal');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Portland Trail Blazers','POR','Biofreeze');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Sacramento Kings','SAC','Blue Diamond Almonds');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('San Antonio Spurs','SAS','Frost Bank');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Toronto Raptors','TOR','Sun Life');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Utah Jazz','UTA','Qualtrics (5 for the fight)');
INSERT INTO sponzorji_1819(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Washington Wizards','WAS','Geico');
