INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Atlanta Hawks','ATL',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Boston Celtics','BOS',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Brooklyn Nets','BKN',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Charlotte Hornets','CHA',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Chicago Bulls','CHI',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Cleveland Cavaliers','CLE',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Dallas Mavericks','DAL',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Denver Nuggets','DEN',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Detroit Pistons','DET',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Golden State Warriors','GSW',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Houston Rockets','HOU',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Indiana Pacers','IND',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Los Angeles Clippers','LAC',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Los Angeles Lakers','LAL',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Memphis Grizzlies','MEM',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Miami Heat','MIA',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Milwaukee Bucks','MIL',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Minnesota Timberwolves','MIN',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('New Orleans Pelicans','NOP',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('New York Knicks','NYK',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Oklahoma City Thunder','OKC',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Orlando Magic','ORL',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Philadelphia 76ers','PHI',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Phoenix Suns','PHX',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Portland Trail Blazers','POR',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Sacramento Kings','SAC',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('San Antonio Spurs','SAS',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Toronto Raptors','TOR',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Utah Jazz','UTA',NULL);
INSERT INTO sponzorji_1617(Ime_ekipe,Kratica,Sponzor_na_dresu) VALUES ('Washington Wizards','WAS',NULL);
